# https://golangci-lint.run/usage/configuration/
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck

issues:
  exclude-rules:
    - linters:
        - revive
      text: "error-strings:"
