---
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w"
archive:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - none*
release:
  prerelease: auto
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Update README
      - Update CHANGELOG
brew:
  github:
    owner: minamijoyo
    name: homebrew-myaws
  commit_author:
    name: "Masayuki Morita"
    email: minamijoyo@gmail.com
  homepage: https://github.com/minamijoyo/myaws
  description: "A human friendly AWS CLI written in Go"
  skip_upload: false
  install: |
    bin.install "myaws"
    output = Utils.popen_read("#{bin}/myaws completion bash")
    (bash_completion/"myaws").write output
    output = Utils.popen_read("#{bin}/myaws completion zsh")
    (zsh_completion/"_myaws").write output
